
IndexError: list index out of range	
# индекс списка вышел за пределы диапазона

TypeError: 'list' object is not callable
# Ответ: print=

TypeError: can only concatenate list (not "int") to list
# Нельзя - объединять список с числом digs2 = digs2 +7

TypeError: '>' not supported between instances of 'int' and 'str'
# Нельзя - число сравнивать с строкой

ValueError: list.remove(x): x not in list
# Метод .remove(True) - нет элемента по значению к удалению22:36 08.06.2021 

Traceback (most recent call last): File "<pyshell#5>", line 1, in <module> A[100] KeyError: 100
# Словарь - коллекция по ключу - неправильный ключ

NameError: name 'd' is not defined
# Словарь - коллекция по ключу - неправильная переменная в которой хранится ключ и значение

TypeError: unhashable type: 'list'
# Словарь - если мы укажем изменяемый тип в качестве ключа 

KeyError: 'popitem(): dictionary is empty'
# Если словарь пуст, то возникает ошибка

ValueError: too many values to unpack (expected 2)
# В кортеже 2 переменные, 3 значения

TypeError: 'tuple' object does not support item assignment
# кортеж - Не можем определенному значению присвоить другое значение

TypeError: 'tuple' object doesn't support item deletion
# кортеж - не можем удалять отдельные элементы из кортежа

ValueError: tuple.index(x): x not in tuple
# кортеж - error - нет элемента в кортеже

none
#  return x - функция возвращает

TypeError: getSquare() takes 2 positional arguments but 3 were given 
# функция def - 3 аргумента, должно быть два

TypeError: getSquare() missing 1 required positional argument: 'h'
# функция def - 1 аргумент, должен быть один

TypeError: theySayHello() missing 1 required positional argument: 'msg1'
# функция def - переопределение функции, аргумент обязательно нужно указывать
# функция def - переопределение функции, может и ненадо в глобальной переменной True , False

Игра сапер
Traceback (most recent call last):
  File "D:\HTML\Python\SelfEdu\python_15_programDesign_up_down.py", line 103, in <module>
    startGame()                    # вызвали эту функцию (1-я итерация создания игры - верхний уровень)
  File "D:\HTML\Python\SelfEdu\python_15_programDesign_up_down.py", line 90, in startGame
    createGame(PM)             # функция будет создавать игровое поле
  File "D:\HTML\Python\SelfEdu\python_15_programDesign_up_down.py", line 38, in createGame
    P[i*N+j] = -1          # иначе в эту клетку запишем -1
NameError: name 'P' is not defined
# функция def createGame(PM): аргумент в формуле должен быть PM ____ строка 38,  line 38

SyntaxError: continue not properly in loop
# continue вне цикла смысла не имеет

ValueError: too many values to unpack (expected 2)
# y3, *z3 = [1, "a", True, 4] - не было знака *,функции с произвольным числом аргументов 

TypeError: 'list' object cannot be interpreted as an integer
# 16. Функция range ожидает два числовых значения, список передавать нельзя for x2 in range(*a)

TypeError: myFuncVocabulary() takes 0 positional arguments but 3 were given
# 16. неименованые аргументы функции

indentationerror: unindent does not match any outer indentation level
# окно gui в Idle  - ошибка возникает, когда вы используете как пробелы, так и табуляцию для отступа в коде

NameError: name 'x' is not defined
# 18. print(x) - обратились к переменной за пределами функции.

name a is assigned to before global declaration
# 18. нельзя работать с локальной переменной после объявления глобальной переменной

no binding for nonlocal "x" found 
# 18. не можем работать так с глобальной переменной

TypeError: 'set' object is not subscriptable
# 19. Обратиться по отдельному индексу к элементу множества НЕ МОЖЕМ

KeyError: 2
# 19. b5.remove(2) - данный метод возвращает ошибку при попытке удаления несуществующего значения, т.к. был удален ранее 

KeyError: 'pop from an empty set'
# 19. c = set()    c.pop()   метод pop для пустого множества

StopIteration
# 20. Дошли  до конца перебираемого списка

TypeError: object of type 'generator' has no len()
# 20. Функция - len() воспользоваться не можем в генераторе выражении

TypeError: 'generator' object is not subscriptable
# 20. b3[2] - не можем получить доступ к отдельному элементу в генераторе выражении

TypeError: squ() missing 1 required positional argument: 'n'
# 21. def sq(x, n):       # функция sq может принимать один аргумент x

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
# 21. print( int(a6) )                    # Error - ф-ция int на входе ожидает конкретной строки а не списка из строк

AttributeError: 'tuple' object has no attribute 'sort'
# 22. # коллекции кортежи или строки - не имеют встроенного метода sort

AttributeError: 'str' object has no attribute 'sort'
# 22. # коллекции кортежи или строки - не имеют встроенного метода sort

TypeError: '<' not supported between instances of 'str' and 'int'
# 22. cортировать только однотипные элементы или только числа, или только строки, или только кортежи
      строки не могут сравниваться с числами

# 23.
# a=[]; a.pop()                   # IndexError: pop from empty list
# 5 / 0                           # ZeroDivisionError: division by zero
# int("12abc")                    # ValueError: invalid literal for int() with base 10: '12abc'
# "2" + 5                         # TypeError: can only concatenate str (not "int") to str

ZeroDivisionError: division by zero
# 23. Если делим на 0 - error: